## YAML configuration file

password: p@ssw0rd

server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: innovateEDU.keystore
      keyStorePassword: p@ssw0rd
      validateCerts: false